# Generated by Django 2.2.24 on 2021-08-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210807_1545'),
        ('recommedations', '0002_auto_20210806_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
