# Generated by Django 2.2.24 on 2021-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210807_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
