# Generated by Django 3.2.4 on 2021-06-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user_id', models.TextField(unique=True)),
                ('wallet_type', models.CharField(choices=[('NG', 'Naira'), ('USD', 'Dollar')], max_length=200)),
                ('wallet_id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('wallet_balance', models.TextField()),
            ],
        ),
    ]
