# Generated by Django 2.2.8 on 2021-06-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210622_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
