# Generated by Django 2.2.8 on 2021-06-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20210623_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('send', 'Send'), ('request', 'Request'), ('transfer', 'Transfer')], default='', max_length=45)),
                ('amount', models.FloatField(default=0.0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='wallet.Wallet')),
                ('receiver', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='wallet.Wallet')),
            ],
        ),
    ]
