# Generated by Django 2.2.8 on 2021-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=60),
        ),
    ]
