# Generated by Django 3.0 on 2021-08-03 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(blank=True, null=True, unique=True, verbose_name='booking date')),
                ('appt_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='appointment date')),
                ('purpose', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accept', 'Accept'), ('cancel', 'Cancel')], max_length=7)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_booked', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_for_appointment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appt_date'],
            },
        ),
    ]
