# Generated by Django 3.2.5 on 2021-07-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='book_date',
            field=models.DateTimeField(blank=True, null=True, unique=True, verbose_name='booking date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accept', 'Accept'), ('cancel', 'Cancel')], max_length=7),
        ),
    ]
